#!/usr/bin/perl
#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks qw(:all);

#
# nethserver-webvirtmgr-update event
#

my $eventupdate = 'nethserver-webvirtmgr-update';

event_actions($eventupdate, qw(
    initialize-default-databases 00
    nethserver-webvirtmgr-conf 20
));

event_templates($eventupdate, qw(
    /usr/lib/python2.6/site-packages/webvirtmgr/conf/gunicorn.conf.py
));

event_services($eventupdate, 'webvirtmgr' => 'restart');
event_services($eventupdate, 'webvirtmgr-novnc' => 'restart');

#
# nethserver-webvirtmgr-save event
#
my $eventsave = 'nethserver-webvirtmgr-save';

event_actions($eventsave, qw(
    nethserver-webvirtmgr-conf 20
));

event_services($eventsave, 'webvirtmgr' => 'restart');
event_services($eventsave, 'webvirtmgr-novnc' => 'restart');
