#!/usr/bin/python
import os
import sys
from subprocess import Popen, PIPE

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "webvirtmgr.settings")

    from django.contrib.auth.models import User
    from user_credentials import *

    (user, stderr) = Popen(["/sbin/e-smith/config",
                            "getprop",
                            "webvirtmgr",
                            "User"], stdout = PIPE).communicate()

    (password, stderr) = Popen(["/sbin/e-smith/config",
                                "getprop",
                                "webvirtmgr",
                                "Password"], stdout = PIPE).communicate()
    email = ""

    user = User.objects.create_user(user, email, password)
    user.is_staff = True
    user.save()
