#!/bin/bash
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#
# set django environment
export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.6/site-packages/Django-1.5.6-py2.6.egg

# create default django db if not exists
if [ ! -f /usr/lib/python2.6/site-packages/webvirtmgr/webvirtmgr.sqlite3 ]; then
    /usr/lib/python2.6/site-packages/webvirtmgr/manage.py syncdb --noinput
fi

# set random password for webvirtmgr admin user
password=`/sbin/e-smith/config getprop webvirtmgr Password`
if [ "x$password" == "x" ]; then
    /sbin/e-smith/config setprop webvirtmgr Password `/usr/bin/openssl rand -base64 12`
    /usr/bin/sqlite3 /usr/lib/python2.6/site-packages/webvirtmgr/webvirtmgr.sqlite3 "INSERT INTO servers_compute VALUES (1,'localhost','localhost','','',4)"
fi

# create webvirtmgr admin user
/usr/lib/python2.6/site-packages/webvirtmgr/webvirtmgr-adduser

exit 0
